apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "2DtWkrcRbTMuWaVL1nMuZUSXEei5MAUPjUJNNVqLydf75urmFxZrNDapXv/2ncLj\ng8mX9Q390P9MRoHqF1QYHGkGDxJ1FGedZbW2CA4HYQjW/g/n8gdk8tVsojnTx5qi\nUa3zj/nNMrIVx+V60GFSKvsUTz2un4QxDIh/pc/3Fws="
