apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "sH4itKTpUGQSXfDpFxuy/wQX59CPa5TZrX66ULYZqGtPP5tzCRen1skvXcc/HL86\noE868AHhRTYiuJYRjkngcZLsBIGb29MlM/gjfI39J9ely8VjE1ntIkRDLy4yLAaL\nN1rYfttXO2awEjavxt41BunTr9vXfYdSaC8rQ0owuc4="
