# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, snyk-testing ]
  pull_request:
    branches: [ master, snyk-testing ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install kubernetes tools
      - name: Install tools
        uses: yokawasa/action-setup-kube-tools@v0.7.1
        with:
          kustomize: '4.1.2'
          kubeval: '0.16.1'
          conftest: '0.18.2'
          kube-score: '1.11.0'
      - name: Test tools
        continue-on-error: true
        run: |
          kustomize build argocd > testing/argocd.yaml && \
          kube-score score --output-format sarif testing/argocd.yaml # > testing/argocd.sarif
      # - name: Upload result to GitHub Code Scanning
      #   uses: github/codeql-action/upload-sarif@v1
      #   with:
      #     sarif_file: testing/argocd.sarif
